# Generated by Django 3.2.7 on 2021-10-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
