# Generated by Django 3.2.7 on 2021-10-22 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('idInvoice', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('paymentMethod', models.CharField(max_length=30, verbose_name='PaymentMethod')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='authApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('idSale', models.AutoField(primary_key=True, serialize=False)),
                ('paymentMethod', models.CharField(max_length=30, verbose_name='PaymentMethod')),
                ('amount', models.IntegerField()),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='authApp.invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='authApp.product')),
            ],
        ),
    ]
