# Generated by Django 3.2.7 on 2021-10-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_auto_20211030_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Cost'),
        ),
    ]
