# Generated by Django 3.2.7 on 2021-11-18 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_sale_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
