from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .ProductView import ProductCreateView
from .ProductView import ProductDeleteView
from .ProductView import ProductReadView
from .ProductView import ProductUpdateView
from .SaleView import SaleCreateView
from .SaleView import SaleDeleteView
from .SaleView import SaleReadView
from .SaleView import SaleUpdateView
from .InvoiceViews import InvoiceCreateView
from .InvoiceViews import InvoiceDeleteView
from .InvoiceViews import InvoiceReadView
from .InvoiceViews import InvoiceUpdateView
